services:
  nextcloud-db:
    image: postgres:16-alpine
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: "sua_senha_segura_aqui"
    volumes:
      - nextcloud_db_data:/var/lib/postgresql/data
    networks:
      - proxy_net
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    networks:
      - proxy_net
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=="sua_senha_segura_aqui"
      - REDIS_HOST=nextcloud-redis
    volumes:
      - nextcloud_data:/var/www/html
      # Se você quiser mapear um diretório externo específico para os arquivos:
      # - /caminho/para/seu/storage:/var/www/html/data
    networks:
      - proxy_net
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 2G

volumes:
  nextcloud_db_data:
  nextcloud_data:

networks:
  proxy_net:
    external: true
