- name: Services
  slug: servicos
  columns:
    - size: small
      widgets:
        - type: bookmarks
          groups:
            - title: Infraestrutura
              links:
                - title: Portainer
                  url: http://localhost:9000
                  icon: si:portainer
                - title: Immich
                  url: http://localhost:2283
                  icon: si:immich

    - size: full
      widgets:
        - type: docker
          socket: /var/run/docker.sock
